name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: SOOJEONGKIMM/productive-box@master
        env:
          GH_TOKEN: ${{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}}
          GIST_ID: ${{31b79f1af43994d914f656daf7daef4f}}
          TIMEZONE: Asia/Seoul
